### ISSUE TITLE
Latest version breaks existing servers

### ISSUE THREAD

**Issue by Benlitz** [Mephi00/v-rising-wine-docker-image#10]
I have a server, created on 2022-05-24 using what was the `latest` image at that time. It is configured using environment variables only (no config file, variables attached below).

After pulling the `latest` image from 2022-06-05, I encounter the following issues: every player would go back to the character creation screen after joining, as if the server had been reset. But all the save files were still there.

I think there is some sort of migration issue with the settings, or something similar. I had backups of the game server so I could investigate a bit, and it seems that after pulling the new image, the file `Saves/v1/save1/SessionId.json` is reset with a new GUID inside, and I believe that's what make the game behave as if the server was reset. The files in `Saves/v1/world1` are unmodified and contain also a json file with a GUID, and about 50 `AutoSave_XXX` subfolders.

Eventually I had to roll back to the previous version of the image (and restore my backup to get the original GUID back in place.
```
Working image: ace25c1be3e0
Problematic image: aaf487cb2bd2
```
File list on the server:
```
./Saves
./Saves/v1
./Saves/v1/save1
./Saves/v1/save1/SessionId.json
./Saves/v1/world1
./Saves/v1/world1/AutoSave_XXX (x50)
./Saves/v1/world1/SessionId.json
```
Used environment variables:
```
V_RISING_CLAN_SIZE 	4
V_RISING_DAY_DURATION_SECONDS 	1080.0
V_RISING_DAY_END_HOUR 	17
V_RISING_DAY_START_HOUR 	9
V_RISING_DEATH_CONTAINER_PERMISSIONS 	Anyone
V_RISING_DESC 	Standard PvE Rules
V_RISING_GAME_MODE 	PvE
V_RISING_MAX_ADMIN 	4
V_RISING_MAX_HEALTH_GLOBAL_MOD 	1.0
V_RISING_MAX_HEALTH_MOD 	1.0
V_RISING_MAX_USER 	40
V_RISING_NAME 	(redacted)
V_RISING_NEST_LIMIT 	4
V_RISING_PASSW 	(redacted)
V_RISING_PORT 	9876
V_RISING_PUBLIC_LIST 	false
V_RISING_QUERY_PORT 	9877
V_RISING_RESOURCE_YIELD_MOD 	1.0
V_RISING_SAVE_NAME 	save1
V_RISING_SETTING_PRESET 	
V_RISING_TOMB_LIMIT 	12
```

**Comment by Mephi00** [comment]
If you change the V_RISING_SAVE_NAME to world1 you will get your old save back. I don't know why it was called the default name "world1" in the first place, but this will fix your problem.

**Comment by Benlitz** [comment]
I didn't have time to play the game for a while, but I tried the above solution today and I just wanted to confirm that it works, thanks!
