### ISSUE TITLE
Error with launch_server.sh

### ISSUE THREAD

**Issue by oscarpedrero** [Mephi00/v-rising-wine-docker-image#14]
failed to execute /launch_server.sh: Permission denied

**Comment by TehGoat** [comment]
Added pull request to fix this #13

**Comment by Toucan-Sam** [comment]
Unfortunately, +1 to the issue.

**Comment by dasmikechen** [comment]
Same.

**Comment by Mephi00** [comment]
Thank you for notifying me, the issue is fixed and the image should be updated within a few minutes
