### ISSUE TITLE
Container cannot update to latest version (no internet)

### ISSUE THREAD

**Issue by olee** [Mephi00/v-rising-wine-docker-image#15]
When the container starts and tries to update to the latest version, I always get this error:`
```
vrising    | [----] Verifying installation...
vrising    | [  0%] Downloading update...
vrising    | [  0%] Checking for available updates...
vrising    | [----] !!! Fatal Error: Steamcmd needs to be online to update. Please confirm your network connection and try again.
```

I tried all kinds of solutions, but none worked so far.

**Comment by Mephi00** [comment]
The container is trying to update the game before starting and needs an internet connection to do so. Are you sure you are connected to the internet?

**Comment by Mephi00** [comment]
Does the container start or is it crashing? This error isn't intended to stop the container from working...

**Comment by sgocken** [comment]
Are you running docker 1.13.1 on el7?
I was getting the same thing before I removed the epel version of docker and installed docker-ce.

**Comment by olee** [comment]
I was able to fix the issue by updating my docker version. Seems like there was an issue with the bit older version I had running.
Sorry for forgetting to close this issue.
