### ISSUE TITLE
Wine: Unhandled exception

### ISSUE THREAD

**Issue by dasmikechen** [Mephi00/v-rising-wine-docker-image#16]
After updating, I am getting the following crash details and cannot build the server:

 A crash has been intercepted by the crash handler. For call stack and other details, see the latest crash report generated in:
 * C:/users/steam/Temp/Stunlock Studios/VRisingServer/Crashes
Stuck main thread detected. Last system started: Unity.Scenes.SceneSectionStreamingSystem. Last system finished: Unity.Scenes.SceneSystemGroup. Last subnode: PrefabGuid: 0 NodeIndex: 0.
UnityEngine.Logger:Log(LogType, Object)
UnityEngine.Debug:Log(Object)
Unity.Entities.<>c__DisplayClass8_0:<Initialize>b__0(Object)
System.Threading.ParameterizedThreadStart:Invoke(Object)
System.Threading.SendOrPostCallback:Invoke(Object)
System.Threading.ExecutionContext:RunInternal(ExecutionContext, ContextCallback, Object, Boolean)
System.Threading.ExecutionContext:Run(ExecutionContext, ContextCallback, Object)
System.Threading.ParameterizedThreadStart:Invoke(Object)

wine: Unhandled exception 0x80000003 in thread 38 at address 0000000180EE7265 (thread 0038), starting debugger...

**Comment by ezruneko** [comment]
Same crash here:

```
A crash has been intercepted by the crash handler. For call stack and other details, see the latest crash report generated in:
 * C:/users/steam/Temp/Stunlock Studios/VRisingServer/Crashes
Stuck main thread detected. Last system started: Unity.Scenes.SceneSectionStreamingSystem. Last system finished: Unity.Scenes.SceneSystemGroup. Last subnode: PrefabGuid: 0 NodeIndex: 0.
UnityEngine.Logger:Log(LogType, Object)
UnityEngine.Debug:Log(Object)
Unity.Entities.<>c__DisplayClass8_0:<Initialize>b__0(Object)
System.Threading.ParameterizedThreadStart:Invoke(Object)
System.Threading.SendOrPostCallback:Invoke(Object)
System.Threading.ExecutionContext:RunInternal(ExecutionContext, ContextCallback, Object, Boolean)
System.Threading.ExecutionContext:Run(ExecutionContext, ContextCallback, Object)
System.Threading.ParameterizedThreadStart:Invoke(Object)
wine: Unhandled exception 0x80000003 in thread 35 at address 0000000180EE7265 (thread 0035), starting debugger...

```

![image](https://user-images.githubusercontent.com/1853429/174469832-b17620a5-8c93-444d-95da-e313baff1533.png)

![image](https://user-images.githubusercontent.com/1853429/174469907-6cd9898f-46c9-464b-b10a-3e8ef80e78b5.png)

**Comment by timdonovanuk** [comment]
Same - is this image dead then?

**Comment by Mephi00** [comment]
I was able to fix these issues with stopping and starting the container again. I haven't encountered this problem for a long time. What specs are you guys running?

**Comment by Mephi00** [comment]
I have found the problem and fixed it, have fun with your image.
