### ISSUE TITLE
Not starting on Synology NAS

### ISSUE THREAD

**Issue by sideh** [Mephi00/v-rising-wine-docker-image#8]
Hello, 

I am having issues getting my Docker Server going from what I understand it is an issue with wine? 

I am trying to run this on my synology NAS, I assume that might be something to do with it?

`Redirecting stderr to '/home/steam/Steam/logs/stderr.txt'`
`[  0%] Checking for available updates...`
`[----] Verifying installation...`
`Steam Console Client (c) Valve Corporation - version 1654028333`
`-- type 'quit' to exit --`
`Loading Steam API...OK`
`"@sSteamCmdForcePlatformType" = "windows"`
`Connecting anonymously to Steam Public...OK`
`Waiting for client config...OK`
`Waiting for user info...OK`
 `Update state (0x5) verifying install, progress: 0.19 (3145728 / 1694433843)`
 `Update state (0x5) verifying install, progress: 21.38 (362257388 / 1694433843)`
 `Update state (0x5) verifying install, progress: 45.34 (768207752 / 1694433843)`
 `Update state (0x5) verifying install, progress: 69.31 (1174396840 / 1694433843)`
 `Update state (0x5) verifying install, progress: 92.89 (1573993621 / 1694433843)`
`Success! App '1829350' fully installed.`
`Using /saves/Settings/ServerGameSettings.json for settings`
`Using /saves/Settings/ServerHostSettings.json for settings`
`(EE) `
`Fatal server error:`
`(EE) Server is already active for display 0`
`	If this server is no longer running, remove /tmp/.X0-lock`
`	and start again.`
`(EE) `
`000f:err:service:process_send_command service protocol error - failed to write pipe!`
`0014:err:winediag:nodrv_CreateWindow Application tried to create a window, but no driver could be loaded.`
`0014:err:winediag:nodrv_CreateWindow The explorer process failed to start.`
`0014:err:ole:apartment_createwindowifneeded CreateWindow failed with error 0`
`0014:err:ole:apartment_createwindowifneeded CreateWindow failed with error 0`
`0014:err:ole:apartment_createwindowifneeded CreateWindow failed with error 0`
`000f:err:service:process_send_command service protocol error - failed to write pipe!`
`000f:err:service:process_send_command service protocol error - failed to write pipe!`

**Comment by Mephi00** [comment]
I suspect this is an error with xvfb. Did the server start or did the container exit? There are some errors upon startup which have to do with wine, but the server still starts and runs without issue.

**Comment by sideh** [comment]
The container just constantly restarts at that point, I don't think the server gets to start at all from what the logs show.

**Comment by Mephi00** [comment]
I will try to update the image in the hopes, this will be fixed in the next few days.

**Comment by sideh** [comment]
Oh that'd be great, thanks for that. 

Is there anything else you need from me to make sure it is the issue?

**Comment by Mephi00** [comment]
I managed to get the container starting on a synology nas. Try to pull the image again and have fun with your V Rising server.
